### ISSUE TITLE
can share the pretained model, and demo for test single image?

### ISSUE THREAD

**Issue by mlinxiang** [z-bingo/kernel-prediction-networks-PyTorch#1]

**Comment by z-bingo** [comment]
okay, I will upload the pretrained model and write the demo in a few days.

**Comment by z-bingo** [comment]
Pretrained model has uploaded tonight, you can clone it to test.

**Comment by mlinxiang** [comment]
@z-bingo thanks a lot

**Comment by mlinxiang** [comment]
@z-bingo  how to run single image?

**Comment by z-bingo** [comment]
The codes for testing the patch has been released, you can write the code to test a single image by yourself. The rest of the code is inconvenient to released recently, sorry.
