### ISSUE TITLE
two question: train datasets and color mode?

### ISSUE THREAD

**Issue by zestloveheart** [z-bingo/kernel-prediction-networks-PyTorch#2]
1. I find the dataset which you specfic in `dataset_specs/full_dataset.conf` is adobe5k. 
I download adobe5k, the dataset's file type is `.dng` which is raw pic type. So....What preprocessing do you run, to convert `.dng` to `.bmp or .jpg` ?

2. Do you finish the color mode? 
I change your code in `train_eval_syn.py`, KPN(color=True),and TrainDataSet(color = True), but it's occurred a error: 
`RuntimeError: Expected 4-dimensional input for 4-dimensional weight 64 27 3 3 0, but got 5-dimensional input of size [32, 9, 3, 128, 128] instead
`

Thank you ~

**Comment by hiterjoshua** [comment]
According to the [blog](https://zhuanlan.zhihu.com/p/73349632)  by the author, I am afraid that this model only supports the Gray mode

**Comment by z-bingo** [comment]
Emmm... I forgot it, too. Maybe the released model only support grayscale image. But you can change the input date shape to suit the color images.

**Comment by amonod** [comment]
Coming a bit late to the party here, but I would also like to get similar data to what was used to train these KPN pytorch models (thank you for making that code available by the way!)

According to `train_eval_syn.py` and` kpn_data_provider.py`, the default training set is the Adobe5k dataset, but the `TrainDataSet` class expects images in `.bmp `format, even though the Adobe5k images are originally in `.dng`. Any chance we could get that data in `.bmp` form?
