### ISSUE TITLE
loading model weights

### ISSUE THREAD

**Issue by kligler** [z-bingo/kernel-prediction-networks-PyTorch#5]
Hey z-Bingo!
I was trying to download and extract the model_best.pth.tar file, though the software I have (7z, Windows 10) fails to extract the file.
might the file be corrupt? Could you provide the weight file in any other compressed format (or just leave uncompressed)?

Thanks
Nati

**Comment by zmlmanly** [comment]
fails to extract the model_best.pth.tar too

**Comment by z-bingo** [comment]
Load the *.pth.tar file directly is okay, don't need to extract it.
